vars:
  PRODUCT_NAME:
    default: Socious
  DISPLAY_NAME:
    default: Socious
  IOS_BUNDLE_ID:
    default: jp.socious.network
  ANDROID_PACKAGE_NAME:
    default: jp.socious.network
  VERSION:
    default: 8.1.0
  IOS_BUILD_NUMBER:
    default: 6
  ANDROID_VERSION_CODE:
    default: 31
  IOS_DEVELOPMENT_TEAM_ID:
    default: 596H9K48FY


platforms:
  ios:
    targets:
      App:
        bundleId: $IOS_BUNDLE_ID
        version: $VERSION
        buildNumber: $IOS_BUILD_NUMBER
        productName: $PRODUCT_NAME
        displayName: $DISPLAY_NAME

        # strings:
        #   - file: ../App.xcodeproj/project.pbxproj
        #     set:
        #       "DEVELOPMENT_TEAM": "DEVELOPMENT_TEAM"
        plist:
          - replace: false
            entries:
              - NSPhotoLibraryUsageDescription: We need access to your photo library to enhance your profile with a picture, share your impactful work, and engage in community activities within the Socious app.
              - UIBackgroundModes:
                  [
                    'remote-notification'
                  ]
        copy:
          - src: ../../GoogleService-Info.plist
            dest: App/GoogleService-Info.plist
          - src: ../../fastlane/ios-config/AppDelegate.swift
            dest: App/AppDelegate.swift

        entitlements:
          - aps-environment: 'development'
          - com.apple.developer.associated-domains:
              [
                'zakaio://platform.proofspace.id'
              ]

  android:
    packageName: $ANDROID_PACKAGE_NAME
    versionName: $VERSION
    versionCode: $ANDROID_VERSION_CODE