name: CD - Release - Android

on:
  push:
    tags:
      - v1.*

jobs:
  setup-fastlane:
    runs-on: ubuntu-latest
    steps:

      - name: Testing the environment
        run: |
          echo ${{ github.ref }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.174.0
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Node.js dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Making Android Release Code
        run: |
          npm run make:android

      - name: Configurating Bundler
        run: |
          gem install bundler
          cp Gemfile ./android

      - name: Installing Fastlane with Bundler
        run: |
          cd android
          bundle update
          bundle install

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Configurating Fastlane
        run: |
          cp -R fastlane/android-config android
          mv android/android-config android/fastlane
          cd android
          sed -i 's|ANDROID_KEY_ALIAS|${{ secrets.ANDROID_KEY_ALIAS }}|g' fastlane/Fastfile
          sed -i 's|ANDROID_KEY_PASSWORD|${{ secrets.ANDROID_KEY_PASSWORD }}|g' fastlane/Fastfile
          sed -i 's|ANDROID_KEY_STORE_PASSWORD|${{ secrets.ANDROID_KEY_STORE_PASSWORD }}|g' fastlane/Fastfile
          echo "${{ secrets.ANDROID_KEY_STORE_BASE64 }}" > AndroidKeystore.jks.base64
          cat AndroidKeystore.jks.base64 | base64 --decode > AndroidKeystore.jks
          fastlane release
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./android/app/release/app-release.apk
          asset_name: Socious-${{ github.ref_name }}.apk
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

      



