name: CD - Release - Android

on:
  push:
    branches:
      - ci
      - main

jobs:
  setup-fastlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.174.0
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          

      - name: Install Node.js dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Making Android Release Code
        run: |
          npm run make:android

      - name: Configurating Bundler
        run: |
          gem install bundler
          cp Gemfile ./android

      - name: Installing Fastlane with Bundler
        run: |
          cd android
          bundle update
          bundle install
          cd ..

      - name: Configurating Fastlane
        run: |
          cp fastlane/android android
          mv android/android-config android/fastlane
          fastlane beta

      - name: Testing the environment
        run: |
          ls
          pwd

      



